### ISSUE TITLE
Import from finviz

### ISSUE THREAD

**Issue by timofey-sadchenko** [HappySeaFox/tht#1]
Is is possible to make so that user get finviz-screen-result without having finviz-elite? for example by simulating Ctrl-C in "tickers" mode

**Comment by HappySeaFox** [comment]
You mean by visiting finviz.com and simulating Ctrl+C there?

**Comment by timofey-sadchenko** [comment]
Dmitry? Nice to know that you are still give attention to this useful utility.
About issue - yes, as you know, it is possible to copy by hand the result of the screening from finviz with a free (non-elite) acc or even without being registered. Now, if you try the adress from finviz, the THT gives a response "incorrect answer" (see screenshot)
![Screenshot_1](https://user-images.githubusercontent.com/62905803/82667823-4012c280-9c41-11ea-8423-2fb83a92528a.png)

**Comment by HappySeaFox** [comment]
Hi! :) I see. The feature you've requested could be implemented, however, as you probably noted in the README, I don't actively develop THT anymore :) Some thoughts for those who may want to implement it:

1. We will need to migrate to Qt5 with a browser engine (QtWebEngine)
2. We will need to distribute the Qt5 browser engine (QtWebEngine) along with THT. That's will increase the size of THT by >100Mb
3. Implementing some Javascripts will also be required to select necessary tickers and copy them
