### ISSUE TITLE
WIN10 system, when switching stocks with the direction button on the keyboard in THT, the Sterling will not follow, but double-clicking the mouse can do.

### ISSUE THREAD

**Issue by kiwi707** [HappySeaFox/tht#4]
WIN10 system, when switching stocks with the direction button on the keyboard in THT, the Sterling will not follow, but double-clicking the mouse can do.

**Comment by HappySeaFox** [comment]
Hi!

I tried on a fresh Win10 install with a Sterling Trader Pro demo. Unfortunately, I was not able to reproduce the issue. See [capture](https://user-images.githubusercontent.com/4995438/131252083-09063c3d-5a97-400e-95df-09a38320d450.mp4).

Just a guess: make sure no third-party software that can alter system windows, their captions, their behavior, or keyboard activity (like xneur) is installed. Try on a fresh Win10 system.
