### ISSUE TITLE
trading statistics Excel file VBA is corrupted

### ISSUE THREAD

**Issue by 75NAeRw2dnCEdxT** [HappySeaFox/tht#5]
Hello,

Looks like the VBA file in the Excel file is corrupted. Upon opening, received the following error:

Microsoft Excel:

The Visual Basic for Applications (VBA) macros in this workbook are corrupted and have been deleted. Then macro corruption most likely exists in the current file. To recover the macros, open a backup copy of this file if you have one.

Any chance to fix that? 
Thanks!

**Comment by HappySeaFox** [comment]
Thanks for the report, I'll try to investigate it.

**Comment by HappySeaFox** [comment]
@75NAeRw2dnCEdxT What Excel version are you using? Please note that the file is written for Excel 2010+. I successfully opened it in Excel 2019.

![image](https://user-images.githubusercontent.com/4995438/140464823-6a41f58c-47f6-4240-b132-a8f68cf8aad0.png)

**Comment by 75NAeRw2dnCEdxT** [comment]
Thanks for a quick response!

Mine is 2019 as well. I can open the file and see pages too, but the VBA code is not working. 

I'll try to reinstall my Office.
